import { DataProvider } from "@hooks/DataContext";
import "./globals.css";
import { Toaster } from "react-hot-toast";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster maxCount={1} />
        <DataProvider>
          <main>{children}</main>
        </DataProvider>
      </body>
    </html>
  );
}
