import Footer from "@components/customComps/Footer";
import Header from "@components/customComps/Header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function AdmidashLayout({ children }) {
  return (
    <section className="flex flex-col min-h-screen">
      <div className="flex flex-col flex-1 ">{children}</div>
    </section>
  );
}
